// Generated by scripts/gen-types.mjs. Do not edit by hand; regenerate after each migration.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "12" }
  public: {
    Tables: {
      addons: {
        Row: {
          applies_to_category_ids: string[]
          description: string | null
          id: string
          name: string
          price_cents: number | null
          price_mode: Database["public"]["Enums"]["price_mode"]
          slug: string
          sort: number
          status: Database["public"]["Enums"]["catalog_status"]
          updated_at: string
        }
        Insert: {
          applies_to_category_ids?: string[]
          description?: string | null
          id?: string
          name: string
          price_cents?: number | null
          price_mode?: Database["public"]["Enums"]["price_mode"]
          slug: string
          sort?: number
          status?: Database["public"]["Enums"]["catalog_status"]
          updated_at?: string
        }
        Update: {
          applies_to_category_ids?: string[]
          description?: string | null
          id?: string
          name?: string
          price_cents?: number | null
          price_mode?: Database["public"]["Enums"]["price_mode"]
          slug?: string
          sort?: number
          status?: Database["public"]["Enums"]["catalog_status"]
          updated_at?: string
        }
        Relationships: [

        ]
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          diff: Json | null
          entity_id: string | null
          entity_type: string
          id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          diff?: Json | null
          entity_id?: string | null
          entity_type: string
          id?: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          diff?: Json | null
          entity_id?: string | null
          entity_type?: string
          id?: string
        }
        Relationships: [

        ]
      }
      blackout_dates: {
        Row: {
          date: string
          id: string
          reason: string | null
        }
        Insert: {
          date: string
          id?: string
          reason?: string | null
        }
        Update: {
          date?: string
          id?: string
          reason?: string | null
        }
        Relationships: [

        ]
      }
      booking_tasks: {
        Row: {
          booking_id: string
          done: boolean
          done_at: string | null
          done_by: string | null
          id: string
          label: string
          sort: number
        }
        Insert: {
          booking_id: string
          done?: boolean
          done_at?: string | null
          done_by?: string | null
          id?: string
          label: string
          sort?: number
        }
        Update: {
          booking_id?: string
          done?: boolean
          done_at?: string | null
          done_by?: string | null
          id?: string
          label?: string
          sort?: number
        }
        Relationships: [
          {
            foreignKeyName: "booking_tasks_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      bookings: {
        Row: {
          cancel_reason: string | null
          client_id: string
          created_at: string
          event_date: string
          event_type: Database["public"]["Enums"]["event_type"]
          expiry_notified_at: string | null
          gallery_url: string | null
          hold_expires_at: string | null
          id: string
          internal_notes: string | null
          period: string
          quote_id: string
          status: Database["public"]["Enums"]["booking_status"]
          thank_you_sent_at: string | null
          title: string
          updated_at: string
          venue_address: string | null
          venue_name: string | null
          zone_id: string | null
        }
        Insert: {
          cancel_reason?: string | null
          client_id: string
          created_at?: string
          event_date: string
          event_type: Database["public"]["Enums"]["event_type"]
          expiry_notified_at?: string | null
          gallery_url?: string | null
          hold_expires_at?: string | null
          id?: string
          internal_notes?: string | null
          period: string
          quote_id: string
          status?: Database["public"]["Enums"]["booking_status"]
          thank_you_sent_at?: string | null
          title: string
          updated_at?: string
          venue_address?: string | null
          venue_name?: string | null
          zone_id?: string | null
        }
        Update: {
          cancel_reason?: string | null
          client_id?: string
          created_at?: string
          event_date?: string
          event_type?: Database["public"]["Enums"]["event_type"]
          expiry_notified_at?: string | null
          gallery_url?: string | null
          hold_expires_at?: string | null
          id?: string
          internal_notes?: string | null
          period?: string
          quote_id?: string
          status?: Database["public"]["Enums"]["booking_status"]
          thank_you_sent_at?: string | null
          title?: string
          updated_at?: string
          venue_address?: string | null
          venue_name?: string | null
          zone_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bookings_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: true
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_zone_id_fkey"
            columns: ["zone_id"]
            isOneToOne: false
            referencedRelation: "service_zones"
            referencedColumns: ["id"]
          },
        ]
      }
      clients: {
        Row: {
          created_at: string
          email: string
          email_normalized: string | null
          full_name: string
          id: string
          notes: string | null
          phone_e164: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string
          email: string
          email_normalized?: never
          full_name: string
          id?: string
          notes?: string | null
          phone_e164?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          email_normalized?: never
          full_name?: string
          id?: string
          notes?: string | null
          phone_e164?: string | null
          user_id?: string | null
        }
        Relationships: [

        ]
      }
      doc_sequences: {
        Row: {
          kind: string
          last_value: number
          year: number
        }
        Insert: {
          kind: string
          last_value?: number
          year: number
        }
        Update: {
          kind?: string
          last_value?: number
          year?: number
        }
        Relationships: [

        ]
      }
      email_log: {
        Row: {
          created_at: string
          entity_id: string | null
          entity_type: string | null
          error: string | null
          id: string
          provider_id: string | null
          status: string
          template: string
          to_email: string
        }
        Insert: {
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          error?: string | null
          id?: string
          provider_id?: string | null
          status: string
          template: string
          to_email: string
        }
        Update: {
          created_at?: string
          entity_id?: string | null
          entity_type?: string | null
          error?: string | null
          id?: string
          provider_id?: string | null
          status?: string
          template?: string
          to_email?: string
        }
        Relationships: [

        ]
      }
      email_templates: {
        Row: {
          body_md: string
          description: string
          key: string
          subject: string
          updated_at: string
        }
        Insert: {
          body_md: string
          description: string
          key: string
          subject: string
          updated_at?: string
        }
        Update: {
          body_md?: string
          description?: string
          key?: string
          subject?: string
          updated_at?: string
        }
        Relationships: [

        ]
      }
      inquiries: {
        Row: {
          client_id: string
          created_at: string
          end_time: string
          estimated_total_cents: number | null
          event_date: string
          event_type: Database["public"]["Enums"]["event_type"]
          guest_count: number | null
          id: string
          notes: string | null
          reference_paths: string[]
          selection: Json
          source: string | null
          start_time: string
          status: Database["public"]["Enums"]["inquiry_status"]
          theme: string | null
          venue_address: string | null
          venue_name: string | null
          zone_id: string | null
        }
        Insert: {
          client_id: string
          created_at?: string
          end_time: string
          estimated_total_cents?: number | null
          event_date: string
          event_type: Database["public"]["Enums"]["event_type"]
          guest_count?: number | null
          id?: string
          notes?: string | null
          reference_paths?: string[]
          selection?: Json
          source?: string | null
          start_time: string
          status?: Database["public"]["Enums"]["inquiry_status"]
          theme?: string | null
          venue_address?: string | null
          venue_name?: string | null
          zone_id?: string | null
        }
        Update: {
          client_id?: string
          created_at?: string
          end_time?: string
          estimated_total_cents?: number | null
          event_date?: string
          event_type?: Database["public"]["Enums"]["event_type"]
          guest_count?: number | null
          id?: string
          notes?: string | null
          reference_paths?: string[]
          selection?: Json
          source?: string | null
          start_time?: string
          status?: Database["public"]["Enums"]["inquiry_status"]
          theme?: string | null
          venue_address?: string | null
          venue_name?: string | null
          zone_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "inquiries_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inquiries_zone_id_fkey"
            columns: ["zone_id"]
            isOneToOne: false
            referencedRelation: "service_zones"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_items: {
        Row: {
          buffer_after_min: number
          buffer_before_min: number
          id: string
          kind: Database["public"]["Enums"]["inventory_kind"]
          name: string
          notes: string | null
          units_owned: number
        }
        Insert: {
          buffer_after_min?: number
          buffer_before_min?: number
          id?: string
          kind: Database["public"]["Enums"]["inventory_kind"]
          name: string
          notes?: string | null
          units_owned?: number
        }
        Update: {
          buffer_after_min?: number
          buffer_before_min?: number
          id?: string
          kind?: Database["public"]["Enums"]["inventory_kind"]
          name?: string
          notes?: string | null
          units_owned?: number
        }
        Relationships: [

        ]
      }
      inventory_reservations: {
        Row: {
          active: boolean
          booking_id: string
          id: string
          inventory_item_id: string
          period: string
          unit_no: number
        }
        Insert: {
          active?: boolean
          booking_id: string
          id?: string
          inventory_item_id: string
          period: string
          unit_no: number
        }
        Update: {
          active?: boolean
          booking_id?: string
          id?: string
          inventory_item_id?: string
          period?: string
          unit_no?: number
        }
        Relationships: [
          {
            foreignKeyName: "inventory_reservations_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_reservations_inventory_item_id_fkey"
            columns: ["inventory_item_id"]
            isOneToOne: false
            referencedRelation: "inventory_items"
            referencedColumns: ["id"]
          },
        ]
      }
      invoices: {
        Row: {
          amount_cents: number
          booking_id: string | null
          client_id: string
          created_at: string
          due_at: string
          etransfer_reference: string
          id: string
          kind: Database["public"]["Enums"]["invoice_kind"]
          last_reminder_at: string | null
          mini_booking_id: string | null
          number: string
          paid_at: string | null
          pdf_path: string | null
          public_token: string
          reported_at: string | null
          status: Database["public"]["Enums"]["invoice_status"]
          tax_cents: number
        }
        Insert: {
          amount_cents: number
          booking_id?: string | null
          client_id: string
          created_at?: string
          due_at: string
          etransfer_reference: string
          id?: string
          kind: Database["public"]["Enums"]["invoice_kind"]
          last_reminder_at?: string | null
          mini_booking_id?: string | null
          number: string
          paid_at?: string | null
          pdf_path?: string | null
          public_token: string
          reported_at?: string | null
          status?: Database["public"]["Enums"]["invoice_status"]
          tax_cents?: number
        }
        Update: {
          amount_cents?: number
          booking_id?: string | null
          client_id?: string
          created_at?: string
          due_at?: string
          etransfer_reference?: string
          id?: string
          kind?: Database["public"]["Enums"]["invoice_kind"]
          last_reminder_at?: string | null
          mini_booking_id?: string | null
          number?: string
          paid_at?: string | null
          pdf_path?: string | null
          public_token?: string
          reported_at?: string | null
          status?: Database["public"]["Enums"]["invoice_status"]
          tax_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "invoices_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invoices_mini_booking_id_fkey"
            columns: ["mini_booking_id"]
            isOneToOne: false
            referencedRelation: "mini_bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      media: {
        Row: {
          alt_text: string
          before_after_role: string | null
          caption: string | null
          category_id: string | null
          created_at: string
          event_type: Database["public"]["Enums"]["event_type"] | null
          featured: boolean
          height: number | null
          id: string
          is_ai_generated: boolean
          is_before_after_pair_id: string | null
          kind: Database["public"]["Enums"]["media_kind"]
          mood_theme: string | null
          show_in_portfolio: boolean
          sort: number
          storage_path: string
          taken_on: string | null
          width: number | null
        }
        Insert: {
          alt_text?: string
          before_after_role?: string | null
          caption?: string | null
          category_id?: string | null
          created_at?: string
          event_type?: Database["public"]["Enums"]["event_type"] | null
          featured?: boolean
          height?: number | null
          id?: string
          is_ai_generated?: boolean
          is_before_after_pair_id?: string | null
          kind?: Database["public"]["Enums"]["media_kind"]
          mood_theme?: string | null
          show_in_portfolio?: boolean
          sort?: number
          storage_path: string
          taken_on?: string | null
          width?: number | null
        }
        Update: {
          alt_text?: string
          before_after_role?: string | null
          caption?: string | null
          category_id?: string | null
          created_at?: string
          event_type?: Database["public"]["Enums"]["event_type"] | null
          featured?: boolean
          height?: number | null
          id?: string
          is_ai_generated?: boolean
          is_before_after_pair_id?: string | null
          kind?: Database["public"]["Enums"]["media_kind"]
          mood_theme?: string | null
          show_in_portfolio?: boolean
          sort?: number
          storage_path?: string
          taken_on?: string | null
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "media_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          body: string
          created_at: string
          email: string
          full_name: string
          handled: boolean
          id: string
          phone_e164: string | null
        }
        Insert: {
          body: string
          created_at?: string
          email: string
          full_name: string
          handled?: boolean
          id?: string
          phone_e164?: string | null
        }
        Update: {
          body?: string
          created_at?: string
          email?: string
          full_name?: string
          handled?: boolean
          id?: string
          phone_e164?: string | null
        }
        Relationships: [

        ]
      }
      mini_bookings: {
        Row: {
          cancel_reason: string | null
          client_id: string
          created_at: string
          expiry_notified_at: string | null
          hold_expires_at: string | null
          id: string
          notes: string | null
          reminder_sent_at: string | null
          slot_id: string
          status: Database["public"]["Enums"]["mini_booking_status"]
        }
        Insert: {
          cancel_reason?: string | null
          client_id: string
          created_at?: string
          expiry_notified_at?: string | null
          hold_expires_at?: string | null
          id?: string
          notes?: string | null
          reminder_sent_at?: string | null
          slot_id: string
          status?: Database["public"]["Enums"]["mini_booking_status"]
        }
        Update: {
          cancel_reason?: string | null
          client_id?: string
          created_at?: string
          expiry_notified_at?: string | null
          hold_expires_at?: string | null
          id?: string
          notes?: string | null
          reminder_sent_at?: string | null
          slot_id?: string
          status?: Database["public"]["Enums"]["mini_booking_status"]
        }
        Relationships: [
          {
            foreignKeyName: "mini_bookings_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mini_bookings_slot_id_fkey"
            columns: ["slot_id"]
            isOneToOne: true
            referencedRelation: "mini_slots"
            referencedColumns: ["id"]
          },
        ]
      }
      mini_campaigns: {
        Row: {
          cover_media_id: string | null
          created_at: string
          description_md: string | null
          duration_min: number
          hold_hours: number
          id: string
          location_address: string | null
          location_name: string | null
          name: string
          payment_mode: Database["public"]["Enums"]["mini_payment_mode"]
          price_cents: number | null
          season: string | null
          slug: string
          status: Database["public"]["Enums"]["campaign_status"]
        }
        Insert: {
          cover_media_id?: string | null
          created_at?: string
          description_md?: string | null
          duration_min?: number
          hold_hours?: number
          id?: string
          location_address?: string | null
          location_name?: string | null
          name: string
          payment_mode?: Database["public"]["Enums"]["mini_payment_mode"]
          price_cents?: number | null
          season?: string | null
          slug: string
          status?: Database["public"]["Enums"]["campaign_status"]
        }
        Update: {
          cover_media_id?: string | null
          created_at?: string
          description_md?: string | null
          duration_min?: number
          hold_hours?: number
          id?: string
          location_address?: string | null
          location_name?: string | null
          name?: string
          payment_mode?: Database["public"]["Enums"]["mini_payment_mode"]
          price_cents?: number | null
          season?: string | null
          slug?: string
          status?: Database["public"]["Enums"]["campaign_status"]
        }
        Relationships: [
          {
            foreignKeyName: "mini_campaigns_cover_media_id_fkey"
            columns: ["cover_media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
        ]
      }
      mini_slots: {
        Row: {
          campaign_id: string
          ends_at: string
          id: string
          starts_at: string
        }
        Insert: {
          campaign_id: string
          ends_at: string
          id?: string
          starts_at: string
        }
        Update: {
          campaign_id?: string
          ends_at?: string
          id?: string
          starts_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "mini_slots_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "mini_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      package_items: {
        Row: {
          package_id: string
          qty: number
          service_id: string
        }
        Insert: {
          package_id: string
          qty?: number
          service_id: string
        }
        Update: {
          package_id?: string
          qty?: number
          service_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "package_items_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "packages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "package_items_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      packages: {
        Row: {
          cover_media_id: string | null
          description_md: string | null
          event_type: Database["public"]["Enums"]["event_type"]
          id: string
          name: string
          price_cents: number | null
          slug: string
          sort: number
          status: Database["public"]["Enums"]["package_status"]
          updated_at: string
        }
        Insert: {
          cover_media_id?: string | null
          description_md?: string | null
          event_type?: Database["public"]["Enums"]["event_type"]
          id?: string
          name: string
          price_cents?: number | null
          slug: string
          sort?: number
          status?: Database["public"]["Enums"]["package_status"]
          updated_at?: string
        }
        Update: {
          cover_media_id?: string | null
          description_md?: string | null
          event_type?: Database["public"]["Enums"]["event_type"]
          id?: string
          name?: string
          price_cents?: number | null
          slug?: string
          sort?: number
          status?: Database["public"]["Enums"]["package_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "packages_cover_media_id_fkey"
            columns: ["cover_media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount_cents: number
          created_at: string
          id: string
          invoice_id: string
          method: Database["public"]["Enums"]["payment_method"]
          note: string | null
          received_at: string
          recorded_by: string | null
        }
        Insert: {
          amount_cents: number
          created_at?: string
          id?: string
          invoice_id: string
          method?: Database["public"]["Enums"]["payment_method"]
          note?: string | null
          received_at?: string
          recorded_by?: string | null
        }
        Update: {
          amount_cents?: number
          created_at?: string
          id?: string
          invoice_id?: string
          method?: Database["public"]["Enums"]["payment_method"]
          note?: string | null
          received_at?: string
          recorded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "invoices"
            referencedColumns: ["id"]
          },
        ]
      }
      policies: {
        Row: {
          body_md: string
          id: string
          key: string
          sort: number
          title: string
          updated_at: string
          version: number
        }
        Insert: {
          body_md: string
          id?: string
          key: string
          sort?: number
          title: string
          updated_at?: string
          version?: number
        }
        Update: {
          body_md?: string
          id?: string
          key?: string
          sort?: number
          title?: string
          updated_at?: string
          version?: number
        }
        Relationships: [

        ]
      }
      quote_lines: {
        Row: {
          description: string
          id: string
          kind: Database["public"]["Enums"]["quote_line_kind"]
          line_total_cents: number
          qty: number
          quote_id: string
          ref_id: string | null
          sort: number
          unit_price_cents: number
        }
        Insert: {
          description: string
          id?: string
          kind: Database["public"]["Enums"]["quote_line_kind"]
          line_total_cents: number
          qty?: number
          quote_id: string
          ref_id?: string | null
          sort?: number
          unit_price_cents: number
        }
        Update: {
          description?: string
          id?: string
          kind?: Database["public"]["Enums"]["quote_line_kind"]
          line_total_cents?: number
          qty?: number
          quote_id?: string
          ref_id?: string | null
          sort?: number
          unit_price_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "quote_lines_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      quotes: {
        Row: {
          accepted_at: string | null
          accepted_ip: string | null
          accepted_name: string | null
          client_id: string
          created_at: string
          deposit_cents: number
          deposit_pct: number
          discount_cents: number
          id: string
          inquiry_id: string
          notes_md: string | null
          number: string | null
          policies_snapshot: Json | null
          public_token: string
          sent_at: string | null
          status: Database["public"]["Enums"]["quote_status"]
          subtotal_cents: number
          tax_cents: number
          tax_rate_bp: number
          total_cents: number
          updated_at: string
          valid_until: string | null
        }
        Insert: {
          accepted_at?: string | null
          accepted_ip?: string | null
          accepted_name?: string | null
          client_id: string
          created_at?: string
          deposit_cents?: number
          deposit_pct?: number
          discount_cents?: number
          id?: string
          inquiry_id: string
          notes_md?: string | null
          number?: string | null
          policies_snapshot?: Json | null
          public_token: string
          sent_at?: string | null
          status?: Database["public"]["Enums"]["quote_status"]
          subtotal_cents?: number
          tax_cents?: number
          tax_rate_bp?: number
          total_cents?: number
          updated_at?: string
          valid_until?: string | null
        }
        Update: {
          accepted_at?: string | null
          accepted_ip?: string | null
          accepted_name?: string | null
          client_id?: string
          created_at?: string
          deposit_cents?: number
          deposit_pct?: number
          discount_cents?: number
          id?: string
          inquiry_id?: string
          notes_md?: string | null
          number?: string | null
          policies_snapshot?: Json | null
          public_token?: string
          sent_at?: string | null
          status?: Database["public"]["Enums"]["quote_status"]
          subtotal_cents?: number
          tax_cents?: number
          tax_rate_bp?: number
          total_cents?: number
          updated_at?: string
          valid_until?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "quotes_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_inquiry_id_fkey"
            columns: ["inquiry_id"]
            isOneToOne: false
            referencedRelation: "inquiries"
            referencedColumns: ["id"]
          },
        ]
      }
      rate_limits: {
        Row: {
          hits: number
          key: string
          window_start: string
        }
        Insert: {
          hits?: number
          key: string
          window_start: string
        }
        Update: {
          hits?: number
          key?: string
          window_start?: string
        }
        Relationships: [

        ]
      }
      service_categories: {
        Row: {
          id: string
          name: string
          slug: string
          sort: number
        }
        Insert: {
          id?: string
          name: string
          slug: string
          sort?: number
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          sort?: number
        }
        Relationships: [

        ]
      }
      service_inventory: {
        Row: {
          inventory_item_id: string
          qty: number
          service_id: string
        }
        Insert: {
          inventory_item_id: string
          qty?: number
          service_id: string
        }
        Update: {
          inventory_item_id?: string
          qty?: number
          service_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_inventory_inventory_item_id_fkey"
            columns: ["inventory_item_id"]
            isOneToOne: false
            referencedRelation: "inventory_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "service_inventory_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      service_zones: {
        Row: {
          description: string | null
          id: string
          name: string
          sort: number
          travel_fee_cents: number | null
        }
        Insert: {
          description?: string | null
          id?: string
          name: string
          sort?: number
          travel_fee_cents?: number | null
        }
        Update: {
          description?: string | null
          id?: string
          name?: string
          sort?: number
          travel_fee_cents?: number | null
        }
        Relationships: [

        ]
      }
      services: {
        Row: {
          category_id: string
          cover_media_id: string | null
          id: string
          included_hours: number | null
          is_public: boolean
          long_desc_md: string | null
          min_hours: number | null
          name: string
          price_cents: number | null
          price_mode: Database["public"]["Enums"]["price_mode"]
          short_desc: string | null
          slug: string
          sort: number
          status: Database["public"]["Enums"]["catalog_status"]
          updated_at: string
        }
        Insert: {
          category_id: string
          cover_media_id?: string | null
          id?: string
          included_hours?: number | null
          is_public?: boolean
          long_desc_md?: string | null
          min_hours?: number | null
          name: string
          price_cents?: number | null
          price_mode?: Database["public"]["Enums"]["price_mode"]
          short_desc?: string | null
          slug: string
          sort?: number
          status?: Database["public"]["Enums"]["catalog_status"]
          updated_at?: string
        }
        Update: {
          category_id?: string
          cover_media_id?: string | null
          id?: string
          included_hours?: number | null
          is_public?: boolean
          long_desc_md?: string | null
          min_hours?: number | null
          name?: string
          price_cents?: number | null
          price_mode?: Database["public"]["Enums"]["price_mode"]
          short_desc?: string | null
          slug?: string
          sort?: number
          status?: Database["public"]["Enums"]["catalog_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "services_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "services_cover_media_id_fkey"
            columns: ["cover_media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
        ]
      }
      settings: {
        Row: {
          address_line: string | null
          balance_due_days_before_event: number
          business_name: string
          city: string
          currency: string
          deposit_pct: number
          email: string | null
          etransfer_autodeposit: boolean
          etransfer_email: string | null
          facebook_review_url: string | null
          facebook_url: string | null
          google_review_url: string | null
          hold_hours: number
          hours_text: string | null
          hst_number: string | null
          id: number
          instagram_url: string | null
          messenger_url: string | null
          owner_name: string
          phone_e164: string | null
          postal_code: string | null
          province: string
          quote_valid_days: number
          reply_to_email: string | null
          tax_enabled: boolean
          tax_rate_bp: number
          timezone: string
          updated_at: string
          whatsapp_e164: string | null
        }
        Insert: {
          address_line?: string | null
          balance_due_days_before_event?: number
          business_name?: string
          city?: string
          currency?: string
          deposit_pct?: number
          email?: string | null
          etransfer_autodeposit?: boolean
          etransfer_email?: string | null
          facebook_review_url?: string | null
          facebook_url?: string | null
          google_review_url?: string | null
          hold_hours?: number
          hours_text?: string | null
          hst_number?: string | null
          id?: number
          instagram_url?: string | null
          messenger_url?: string | null
          owner_name?: string
          phone_e164?: string | null
          postal_code?: string | null
          province?: string
          quote_valid_days?: number
          reply_to_email?: string | null
          tax_enabled?: boolean
          tax_rate_bp?: number
          timezone?: string
          updated_at?: string
          whatsapp_e164?: string | null
        }
        Update: {
          address_line?: string | null
          balance_due_days_before_event?: number
          business_name?: string
          city?: string
          currency?: string
          deposit_pct?: number
          email?: string | null
          etransfer_autodeposit?: boolean
          etransfer_email?: string | null
          facebook_review_url?: string | null
          facebook_url?: string | null
          google_review_url?: string | null
          hold_hours?: number
          hours_text?: string | null
          hst_number?: string | null
          id?: number
          instagram_url?: string | null
          messenger_url?: string | null
          owner_name?: string
          phone_e164?: string | null
          postal_code?: string | null
          province?: string
          quote_valid_days?: number
          reply_to_email?: string | null
          tax_enabled?: boolean
          tax_rate_bp?: number
          timezone?: string
          updated_at?: string
          whatsapp_e164?: string | null
        }
        Relationships: [

        ]
      }
      testimonials: {
        Row: {
          approved: boolean
          booking_id: string | null
          client_id: string | null
          client_name: string
          consent_to_publish: boolean
          created_at: string
          event_type: Database["public"]["Enums"]["event_type"] | null
          id: string
          quote: string
          rating: number | null
          source: Database["public"]["Enums"]["testimonial_source"]
        }
        Insert: {
          approved?: boolean
          booking_id?: string | null
          client_id?: string | null
          client_name: string
          consent_to_publish?: boolean
          created_at?: string
          event_type?: Database["public"]["Enums"]["event_type"] | null
          id?: string
          quote: string
          rating?: number | null
          source?: Database["public"]["Enums"]["testimonial_source"]
        }
        Update: {
          approved?: boolean
          booking_id?: string | null
          client_id?: string | null
          client_name?: string
          consent_to_publish?: boolean
          created_at?: string
          event_type?: Database["public"]["Enums"]["event_type"] | null
          id?: string
          quote?: string
          rating?: number | null
          source?: Database["public"]["Enums"]["testimonial_source"]
        }
        Relationships: [
          {
            foreignKeyName: "testimonials_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "testimonials_client_id_fkey"
            columns: ["client_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
        ]
      }
      user_roles: {
        Row: {
          created_at: string
          display_name: string | null
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: [

        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_quote: {
        Args: { p_token: string; p_name: string; p_ip: string }
        Returns: Json
      }
      auth_role: {
        Args: never
        Returns: string
      }
      complete_past_bookings: {
        Args: never
        Returns: number
      }
      create_balance_invoice: {
        Args: { p_booking_id: string }
        Returns: string
      }
      event_period: {
        Args: { p_date: string; p_start: string; p_end: string }
        Returns: string
      }
      expire_stale_holds: {
        Args: never
        Returns: number
      }
      hit_rate_limit: {
        Args: { p_key: string; p_max: number; p_window_seconds: number }
        Returns: boolean
      }
      hold_mini_slot: {
        Args: { p_slot_id: string; p_client_id: string; p_notes: string }
        Returns: Json
      }
      is_owner: {
        Args: never
        Returns: boolean
      }
      is_team: {
        Args: never
        Returns: boolean
      }
      link_my_client_account: {
        Args: never
        Returns: number
      }
      mini_slot_availability: {
        Args: { p_campaign_id: string }
        Returns: {
          slot_id: string
          starts_at: string
          ends_at: string
          is_open: boolean
        }[]
      }
      moncton_today: {
        Args: never
        Returns: string
      }
      my_client_ids: {
        Args: never
        Returns: string[]
      }
      next_doc_number: {
        Args: { p_kind: string }
        Returns: string
      }
      public_settings: {
        Args: never
        Returns: {
          business_name: string
          owner_name: string
          phone_e164: string
          email: string
          whatsapp_e164: string
          messenger_url: string
          facebook_url: string
          instagram_url: string
          address_line: string
          city: string
          province: string
          postal_code: string
          hours_text: string
          timezone: string
          currency: string
          deposit_pct: number
          hold_hours: number
          balance_due_days_before_event: number
          tax_enabled: boolean
          tax_rate_bp: number
          google_review_url: string
          facebook_review_url: string
        }[]
      }
      quote_inventory_needs: {
        Args: { p_quote_id: string }
        Returns: {
          inventory_item_id: string
          item_name: string
          qty: number
        }[]
      }
      random_token: {
        Args: never
        Returns: string
      }
      record_payment: {
        Args: { p_invoice_id: string; p_method: Database["public"]["Enums"]["payment_method"]; p_amount_cents: number; p_received_at: string; p_note: string; p_actor: string }
        Returns: Json
      }
      report_invoice_payment: {
        Args: { p_token: string }
        Returns: Json
      }
      service_availability: {
        Args: { p_date: string; p_start: string; p_end: string }
        Returns: {
          service_id: string
          slug: string
          status: string
          reason: string
        }[]
      }
    }
    Enums: {
      app_role: "owner" | "staff"
      booking_status: "held" | "confirmed" | "completed" | "cancelled"
      campaign_status: "draft" | "live" | "closed"
      catalog_status: "draft" | "needs_price" | "active" | "archived"
      event_type: "wedding" | "birthday" | "baby_shower" | "corporate" | "graduation" | "other"
      inquiry_status: "new" | "quoted" | "won" | "lost" | "spam"
      inventory_kind: "mirror_booth" | "booth_360" | "video_guestbook" | "arch" | "table_set" | "staff" | "other"
      invoice_kind: "deposit" | "balance" | "full" | "mini"
      invoice_status: "unpaid" | "reported" | "paid" | "void"
      media_kind: "photo" | "video"
      mini_booking_status: "held" | "confirmed" | "cancelled" | "no_show"
      mini_payment_mode: "deposit" | "full"
      package_status: "draft" | "active" | "archived"
      payment_method: "etransfer" | "cash" | "other"
      price_mode: "flat" | "per_hour" | "per_item" | "from"
      quote_line_kind: "package" | "service" | "addon" | "travel" | "custom"
      quote_status: "draft" | "sent" | "accepted" | "declined" | "expired" | "superseded"
      testimonial_source: "site" | "facebook" | "google"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]

export const Constants = {
  public: {
    Enums: {
      app_role: ["owner","staff"],
      booking_status: ["held","confirmed","completed","cancelled"],
      campaign_status: ["draft","live","closed"],
      catalog_status: ["draft","needs_price","active","archived"],
      event_type: ["wedding","birthday","baby_shower","corporate","graduation","other"],
      inquiry_status: ["new","quoted","won","lost","spam"],
      inventory_kind: ["mirror_booth","booth_360","video_guestbook","arch","table_set","staff","other"],
      invoice_kind: ["deposit","balance","full","mini"],
      invoice_status: ["unpaid","reported","paid","void"],
      media_kind: ["photo","video"],
      mini_booking_status: ["held","confirmed","cancelled","no_show"],
      mini_payment_mode: ["deposit","full"],
      package_status: ["draft","active","archived"],
      payment_method: ["etransfer","cash","other"],
      price_mode: ["flat","per_hour","per_item","from"],
      quote_line_kind: ["package","service","addon","travel","custom"],
      quote_status: ["draft","sent","accepted","declined","expired","superseded"],
      testimonial_source: ["site","facebook","google"],
    },
  },
} as const
