#!/usr/bin/env node
// Generates src/lib/database.types.ts from a database in the same shape as
// `supabase gen types typescript`. Use the Supabase CLI against your project when
// you can (`npm run types:supabase`); this script exists so types can be
// regenerated from a plain local Postgres (scripts/db-reset-local.sh) without Docker.
//
//   DATABASE_URL=postgresql://tester:tester@localhost:5432/fmv_test node scripts/gen-types.mjs

import pg from 'pg';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const url = process.env.DATABASE_URL ?? 'postgresql://tester:tester@localhost:5432/fmv_test';
const out = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'database.types.ts');
const client = new pg.Client({ connectionString: url });
await client.connect();

const enums = (await client.query(`
  select t.typname as name, array_agg(e.enumlabel::text order by e.enumsortorder) as labels
  from pg_type t join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' group by t.typname order by t.typname`)).rows;
const enumNames = new Set(enums.map((e) => e.name));

function tsType(udt, isArray = false) {
  const base = udt.replace(/^_/, '');
  let t;
  if (enumNames.has(base)) t = `Database["public"]["Enums"]["${base}"]`;
  else if (['int2', 'int4', 'int8', 'float4', 'float8', 'numeric'].includes(base)) t = 'number';
  else if (base === 'bool') t = 'boolean';
  else if (['json', 'jsonb'].includes(base)) t = 'Json';
  else if (base === 'void') t = 'undefined';
  else t = 'string';
  return isArray || udt.startsWith('_') ? `${t}[]` : t;
}

const cols = (await client.query(`
  select c.table_name, c.column_name, c.udt_name, c.is_nullable = 'YES' as nullable,
         c.column_default is not null as has_default, c.is_generated = 'ALWAYS' as generated,
         c.is_identity = 'YES' as identity
  from information_schema.columns c
  join information_schema.tables t on t.table_name = c.table_name and t.table_schema = c.table_schema
  where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
  order by c.table_name, c.column_name`)).rows;

const fks = (await client.query(`
  select con.conname, rel.relname as table_name, frel.relname as ref_table,
         array(select a.attname::text from unnest(con.conkey) k join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k) as columns,
         array(select a.attname::text from unnest(con.confkey) k join pg_attribute a on a.attrelid = con.confrelid and a.attnum = k) as ref_columns,
         exists (select 1 from pg_index i where i.indrelid = con.conrelid and i.indisunique
                 and (select array_agg(x order by x) from unnest(i.indkey::int2[]) x) = (select array_agg(x order by x) from unnest(con.conkey) x)) as one_to_one
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_class frel on frel.oid = con.confrelid
  join pg_namespace n on n.oid = rel.relnamespace
  join pg_namespace fn on fn.oid = frel.relnamespace
  where con.contype = 'f' and n.nspname = 'public' and fn.nspname = 'public'
  order by con.conname`)).rows;

const fns = (await client.query(`
  select p.proname as name, p.proretset as retset,
         pg_get_function_identity_arguments(p.oid) as identity_args,
         coalesce(p.proargnames, '{}') as argnames, coalesce(p.proargmodes::text[], '{}') as argmodes,
         coalesce(p.proallargtypes, p.proargtypes::oid[])::int8[] as argtypes,
         rt.typname as rettype, p.pronargdefaults as ndefaults, p.pronargs as nargs
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  join pg_type rt on rt.oid = p.prorettype
  where n.nspname = 'public' and rt.typname <> 'trigger' and p.prokind = 'f'
  order by p.proname`)).rows;

async function typname(oid) {
  return (await client.query('select typname from pg_type where oid = $1', [oid])).rows[0].typname;
}

const tables = {};
for (const c of cols) (tables[c.table_name] ??= []).push(c);

let s = `// Generated by scripts/gen-types.mjs. Do not edit by hand; regenerate after each migration.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "12" }
  public: {
    Tables: {
`;
for (const [name, columns] of Object.entries(tables)) {
  const row = columns.map((c) => `          ${c.column_name}: ${tsType(c.udt_name)}${c.nullable ? ' | null' : ''}`).join('\n');
  const ins = columns.map((c) => {
    if (c.generated) return `          ${c.column_name}?: never`;
    const opt = c.nullable || c.has_default || c.identity ? '?' : '';
    return `          ${c.column_name}${opt}: ${tsType(c.udt_name)}${c.nullable ? ' | null' : ''}`;
  }).join('\n');
  const upd = columns.map((c) => c.generated
    ? `          ${c.column_name}?: never`
    : `          ${c.column_name}?: ${tsType(c.udt_name)}${c.nullable ? ' | null' : ''}`).join('\n');
  const rels = fks.filter((f) => f.table_name === name).map((f) => `          {
            foreignKeyName: "${f.conname}"
            columns: ${JSON.stringify(f.columns)}
            isOneToOne: ${f.one_to_one}
            referencedRelation: "${f.ref_table}"
            referencedColumns: ${JSON.stringify(f.ref_columns)}
          },`).join('\n');
  s += `      ${name}: {
        Row: {
${row}
        }
        Insert: {
${ins}
        }
        Update: {
${upd}
        }
        Relationships: [
${rels}
        ]
      }
`;
}
s += `    }
    Views: {
      [_ in never]: never
    }
    Functions: {
`;
for (const f of fns) {
  const args = [];
  const outCols = [];
  const nIn = f.argmodes.length ? f.argmodes.filter((m) => m === 'i' || m === 'b').length : f.nargs;
  let inIdx = 0;
  for (let i = 0; i < f.argtypes.length; i++) {
    const mode = f.argmodes[i] ?? 'i';
    const t = await typname(f.argtypes[i]);
    const nm = f.argnames[i] ?? `arg${i}`;
    if (mode === 'i' || mode === 'b') {
      const optional = inIdx >= nIn - f.ndefaults;
      args.push(`${nm}${optional ? '?' : ''}: ${tsType(t)}`);
      inIdx++;
    }
    if (mode === 'o' || mode === 't' || mode === 'b') outCols.push(`${nm}: ${tsType(t)}`);
  }
  let ret;
  if (outCols.length) ret = `{\n          ${outCols.join('\n          ')}\n        }[]`;
  else ret = tsType(f.rettype) + (f.retset ? '[]' : '');
  s += `      ${f.name}: {
        Args: ${args.length ? `{ ${args.join('; ')} }` : 'never'}
        Returns: ${ret}
      }
`;
}
s += `    }
    Enums: {
${enums.map((e) => `      ${e.name}: ${e.labels.map((l) => JSON.stringify(l)).join(' | ')}`).join('\n')}
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]

export const Constants = {
  public: {
    Enums: {
${enums.map((e) => `      ${e.name}: ${JSON.stringify(e.labels)},`).join('\n')}
    },
  },
} as const
`;
writeFileSync(out, s);
await client.end();
console.log(`Wrote ${out} (${Object.keys(tables).length} tables, ${fns.length} functions, ${enums.length} enums)`);
