-- Default email templates. Editable in /admin/emails. Merge tags use {{tag}}.

insert into public.email_templates (key, description, subject, body_md) values
('inquiry_received_client', 'To the client after they submit the event builder',
 'We received your event request – {{business_name}}',
 E'Hi {{client_name}},\n\nThank you for reaching out! We received your request for **{{event_type}}** on **{{event_date}}**.\n\nYour estimate was **{{estimate}}**. {{owner_name}} will review the details and send your personalised quote shortly. No date is held yet: your date is reserved once you accept the quote and the deposit is received.\n\nTalk soon,\n{{owner_name}} · {{business_name}}'),
('inquiry_received_owner', 'Alert to the owner about a new inquiry',
 'New inquiry: {{event_type}} on {{event_date}}',
 E'**{{client_name}}** ({{client_email}}, {{client_phone}}) sent a new inquiry.\n\n- Event: {{event_type}} on {{event_date}}, {{event_time}}\n- Venue: {{venue}}\n- Estimate: {{estimate}}\n\n[Open in admin]({{admin_url}})'),
('quote_sent', 'Quote link to the client',
 'Your quote {{quote_number}} from {{business_name}}',
 E'Hi {{client_name}},\n\nYour quote for **{{event_date}}** is ready: **{{total}}**, with a **{{deposit}}** deposit to confirm your date.\n\n[View and accept your quote]({{quote_url}})\n\nThis quote is valid until {{valid_until}}.\n\n{{owner_name}} · {{business_name}}'),
('quote_accepted', 'Deposit invoice after the client accepts',
 'Your date is held – deposit invoice {{invoice_number}}',
 E'Hi {{client_name}},\n\nThank you for accepting your quote! Your date (**{{event_date}}**) is **held until {{due}}**.\n\nTo confirm it, please send the deposit of **{{amount}}** by Interac e-Transfer and put **{{reference}}** in the message.\n\n[Open your pay page]({{pay_url}})\n\nYour invoice PDF is attached.\n\n{{owner_name}} · {{business_name}}'),
('payment_reported_owner', 'Alert to the owner when a client taps "I''ve sent it"',
 'Payment reported: {{reference}} ({{amount}})',
 E'**{{client_name}}** says they sent **{{amount}}** for invoice {{invoice_number}} (reference **{{reference}}**).\n\nCheck your bank, then record the payment in the admin to confirm the booking.\n\n[Record payment]({{admin_url}})'),
('booking_confirmed', 'After the owner records the deposit',
 'You''re confirmed! {{event_date}} with {{business_name}}',
 E'Hi {{client_name}},\n\nWe received your payment of **{{amount}}**. Your date (**{{event_date}}**) is **confirmed**.\n\n{{balance_line}}\n\nYou can see your booking and invoices any time in your [client portal]({{portal_url}}).\n\n{{owner_name}} · {{business_name}}'),
('hold_expired', 'When an unpaid hold is released',
 'Your date hold has expired',
 E'Hi {{client_name}},\n\nWe didn''t receive the deposit in time, so the hold on **{{event_date}}** has been released.\n\nStill want to book? [Start again here]({{rebook_url}}) or reply to this email and we''ll help.\n\n{{owner_name}} · {{business_name}}'),
('balance_reminder', 'Balance reminder (3 days before due and on the due date)',
 'Balance reminder – {{amount}} due {{due}}',
 E'Hi {{client_name}},\n\nA friendly reminder: the balance of **{{amount}}** for your event on **{{event_date}}** is due **{{due}}**.\n\nPlease send it by Interac e-Transfer with **{{reference}}** in the message.\n\n[Open your pay page]({{pay_url}})\n\n{{owner_name}} · {{business_name}}'),
('mini_held', 'Mini-session slot held, with pay link',
 'Your {{campaign_name}} spot is held',
 E'Hi {{client_name}},\n\nYour mini session on **{{slot_time}}** at {{location}} is held until **{{due}}**.\n\nPlease send **{{amount}}** by Interac e-Transfer with **{{reference}}** in the message to confirm it.\n\n[Open your pay page]({{pay_url}})\n\n{{owner_name}} · {{business_name}}'),
('mini_confirmed', 'Mini session confirmed (with .ics attached)',
 'Confirmed: {{campaign_name}} on {{slot_time}}',
 E'Hi {{client_name}},\n\nYour mini session is **confirmed** for **{{slot_time}}** at {{location}}. A calendar invite is attached.\n\nSee you soon!\n\n{{owner_name}} · {{business_name}}'),
('mini_reminder', 'Reminder 24 hours before a mini session',
 'See you tomorrow – {{campaign_name}}',
 E'Hi {{client_name}},\n\nJust a reminder that your mini session is **{{slot_time}}** at {{location}}.\n\n{{owner_name}} · {{business_name}}'),
('mini_hold_expired', 'When an unpaid mini-session hold is released',
 'Your mini-session hold has expired',
 E'Hi {{client_name}},\n\nWe didn''t receive payment in time, so your held spot ({{slot_time}}) has been released. If spots are still open you can [pick a new time]({{rebook_url}}).\n\n{{owner_name}} · {{business_name}}'),
('thank_you', 'After the event: thank-you, review request and gallery',
 'Thank you from {{business_name}}',
 E'Hi {{client_name}},\n\nThank you for celebrating with us! It was a joy to be part of your event.\n\n{{gallery_line}}\n\nIf you have a minute, a short review means the world to a small local business:\n\n{{review_links}}\n\n{{owner_name}} · {{business_name}}'),
('message_received_owner', 'General question from the contact form',
 'New question from {{client_name}}',
 E'**{{client_name}}** ({{client_email}}, {{client_phone}}) asked:\n\n{{message}}\n\n[Open in admin]({{admin_url}})')
on conflict (key) do nothing;
